/* COMMENTS TABLE */
DROP TABLE IF EXISTS comments;

CREATE TABLE comments(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poster VARCHAR,
  comment VARCHAR,
  date BIGINT
);

CREATE INDEX posterIndex ON comments (poster);
CREATE INDEX commentIndex ON comments (comment);
CREATE INDEX dateIndexComments ON comments (date);

SELECT setval('comments_id_seq', max(id)) FROM comments;





DROP TABLE IF EXISTS visitors;

CREATE TABLE visitors(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ipAddr VARCHAR,
  date BIGINT
);

CREATE INDEX ipIndex ON visitors (ipAddr);
CREATE INDEX dateIndexVisitors ON visitors (date);

SELECT setval('visitors_id_seq', max(id)) FROM visitors;