/* COMMENTS TABLE */

CREATE TABLE comments(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poster VARCHAR,
  comment VARCHAR
);

CREATE INDEX posterIndex ON comments (poster);
CREATE INDEX commentIndex ON comments (comment);

SELECT setval('comments_id_seq', max(id)) FROM comments;